add_newline = false

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 30
style = "bold yellow"


