theme = "nord-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]
max_width = 20
marquee = true
marquee_interval = 10
marquee_speed = 0.2
smart_trim = false
separator = " - "
on_collapsed_click = "spotify"

[[block]]
block = "sound"
step_width = 5
on_click = "amixer -D pulse sset Master toggle"
#format = "{output_description} {volume}"
format = "{volume}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}"

[[block]]
block = "memory"
interval = 5
display_type = "memory"
format_mem = "{mem_used}"
format_swap = "{swap_used}"
icons = true

[[block]]
block = "net"
format = "{ssid}"
format_alt = "{ssid} {signal_strength} {ip} {speed_down;K*b} {graph_down;K} {speed_up;K*b} {graph_up;K}"
interval = 5

[[block]]
block = "backlight"
device = "intel_backlight"
step_width = 5
invert_icons = true

[[block]]
block = "temperature"
scale = "celsius"
collapsed = false
format = "{average}"
good = 25
idle = 45
info = 65
warning = 80

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
alert_absolute = true
interval = 30
warning = 15
alert = 7
format = "/: {available}"

#[[block]]
#block = "disk_space"
#path = "/home/birromer"
#info_type = "available"
#unit = "GB"
#interval = 30
#alert_absolute = true
#warning = 20
#alert = 10
#format = "~: {available}"

[[block]]
block = "battery"
interval = 10
device = "BAT1"
format = "{percentage} {time}"
full_threshold = 84
good = 60
warning = 25
critical = 10

[[block]]
block = "time"
timezone = "Europe/Paris"
interval = 5
format = "%d-%m-%y %H:%M"
#format = "%a %d/%m %R"

[[block]]
block = "watson"
show_time = true
state_path = "/home/birromer/.config/watson/state"

[[block]]
block = "toggle"
text = "ext"
#command_state = "xrandr --listactivemonitors | grep DP1 | grep -v eDP1"
command_state = "xrandr --listactivemonitors | grep DP1-2 | grep -v eDP1"
#command_on = "~/.screenlayout/external.sh"
command_on = "~/.screenlayout/external_inria.sh"
command_off = "~/.screenlayout/laptop.sh"
interval = 10

# overrides in themes and icons
#[theme]
#name = "solarized-dark"
#[theme.overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"
